mod SPEC is
  protecting INT .
  protecting STRING .
  sorts BoolV Command Expr Id IntV List Literal NatV Opt Pair Text Type Val .
  subsorts BoolV Command Expr Id IntV List Literal NatV Opt Pair Text Type < Val .
  subsort Id < Expr .
  subsort List < Text .
  subsort Literal < Expr .

  op $itermap-K-t-minus-gt-V-t-list-2-pair : Val Val -> Val .
  op $lookup : List Val -> Opt .
  op $unzip-K-t-minus-gt-V-t-list-K-t : Val -> Val .
  op $unzip-K-t-minus-gt-V-t-list-V-t : Val -> Val .
  op Check-command : List Command -> List .
  op Check-expr : List Expr -> Type .
  op Check-prog : Command -> BoolV .
  op Eval-command : List Command -> List .
  op Eval-expr : List Expr -> Literal .
  op Eval-prog : Command -> List .
  op Run-prog : Command -> List .
  op add-int : IntV IntV -> IntV .
  op and : BoolV BoolV -> BoolV .
  op bool : Bool -> BoolV .
  op cons : Val List -> List .
  op int : Int -> IntV .
  op isStuckHead : Val -> Bool .
  op leq-int : IntV IntV -> BoolV .
  op match-command-IF-THEN-ELSE-END-3 : Command -> BoolV .
  op match-command-SKIP-0 : Command -> BoolV .
  op match-command-WHILE-DO-END-2 : Command -> BoolV .
  op match-command-eq-2 : Command -> BoolV .
  op match-command-eq-3 : Command -> BoolV .
  op match-command-semi-2 : Command -> BoolV .
  op match-cons : List -> BoolV .
  op match-expr-amp-amp-2 : Expr -> BoolV .
  op match-expr-bang-1 : Expr -> BoolV .
  op match-expr-lt-eq-2 : Expr -> BoolV .
  op match-expr-plus-2 : Expr -> BoolV .
  op match-literal-BOOL-1 : Literal -> BoolV .
  op match-literal-NUM-1 : Literal -> BoolV .
  op match-nil : List -> BoolV .
  op match-some : Opt -> BoolV .
  op match-type-BOOL-0 : Type -> BoolV .
  op match-type-INT-0 : Type -> BoolV .
  op nat : Nat -> NatV .
  op nil : -> List .
  op none : -> Opt .
  op not : BoolV -> BoolV .
  op some : Val -> Opt .
  op subty-id : Val -> BoolV .
  op subty-literal : Val -> BoolV .
  op txt : String -> Text .
  op variant-command-IF-THEN-ELSE-END-3 : Expr Command Command -> Command .
  op variant-command-SKIP-0 : -> Command .
  op variant-command-WHILE-DO-END-2 : Expr Command -> Command .
  op variant-command-eq-2 : Id Expr -> Command .
  op variant-command-eq-3 : Type Id Expr -> Command .
  op variant-command-semi-2 : Command Command -> Command .
  op variant-expr-amp-amp-2 : Expr Expr -> Expr .
  op variant-expr-bang-1 : Expr -> Expr .
  op variant-expr-lt-eq-2 : Expr Expr -> Expr .
  op variant-expr-plus-2 : Expr Expr -> Expr .
  op variant-id-ID-1 : Text -> Id .
  op variant-literal-BOOL-1 : BoolV -> Literal .
  op variant-literal-NUM-1 : IntV -> Literal .
  op variant-pair-minus-gt-2 : Val Val -> Pair .
  op variant-type-BOOL-0 : -> Type .
  op variant-type-INT-0 : -> Type .

  eq match-some(some(x:Val)) = bool(true) .
  eq match-some(none) = bool(false) .
  eq match-cons(cons(x:Val, xs:List)) = bool(true) .
  eq match-cons(nil) = bool(false) .
  eq match-nil(nil) = bool(true) .
  eq match-nil(cons(x:Val, xs:List)) = bool(false) .
  eq match-type-INT-0(variant-type-INT-0) = bool(true) .
  eq match-type-INT-0(variant-type-BOOL-0) = bool(false) .
  eq match-type-BOOL-0(variant-type-INT-0) = bool(false) .
  eq match-type-BOOL-0(variant-type-BOOL-0) = bool(true) .
  eq match-literal-NUM-1(variant-literal-NUM-1(x0:IntV)) = bool(true) .
  eq match-literal-NUM-1(variant-literal-BOOL-1(x0:BoolV)) = bool(false) .
  eq match-literal-BOOL-1(variant-literal-NUM-1(x0:IntV)) = bool(false) .
  eq match-literal-BOOL-1(variant-literal-BOOL-1(x0:BoolV)) = bool(true) .
  eq subty-literal(variant-literal-NUM-1(x0:IntV)) = bool(true) .
  eq subty-literal(variant-literal-BOOL-1(x0:BoolV)) = bool(true) .
  eq subty-id(variant-id-ID-1(x0:Text)) = bool(true) .
  eq match-expr-bang-1(variant-literal-NUM-1(x0:IntV)) = bool(false) .
  eq match-expr-bang-1(variant-literal-BOOL-1(x0:BoolV)) = bool(false) .
  eq match-expr-bang-1(variant-id-ID-1(x0:Text)) = bool(false) .
  eq match-expr-bang-1(variant-expr-bang-1(x0:Expr)) = bool(true) .
  eq match-expr-bang-1(variant-expr-plus-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-bang-1(variant-expr-lt-eq-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-bang-1(variant-expr-amp-amp-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-plus-2(variant-literal-NUM-1(x0:IntV)) = bool(false) .
  eq match-expr-plus-2(variant-literal-BOOL-1(x0:BoolV)) = bool(false) .
  eq match-expr-plus-2(variant-id-ID-1(x0:Text)) = bool(false) .
  eq match-expr-plus-2(variant-expr-bang-1(x0:Expr)) = bool(false) .
  eq match-expr-plus-2(variant-expr-plus-2(x0:Expr, x1:Expr)) = bool(true) .
  eq match-expr-plus-2(variant-expr-lt-eq-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-plus-2(variant-expr-amp-amp-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-lt-eq-2(variant-literal-NUM-1(x0:IntV)) = bool(false) .
  eq match-expr-lt-eq-2(variant-literal-BOOL-1(x0:BoolV)) = bool(false) .
  eq match-expr-lt-eq-2(variant-id-ID-1(x0:Text)) = bool(false) .
  eq match-expr-lt-eq-2(variant-expr-bang-1(x0:Expr)) = bool(false) .
  eq match-expr-lt-eq-2(variant-expr-plus-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-lt-eq-2(variant-expr-lt-eq-2(x0:Expr, x1:Expr)) = bool(true) .
  eq match-expr-lt-eq-2(variant-expr-amp-amp-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-amp-amp-2(variant-literal-NUM-1(x0:IntV)) = bool(false) .
  eq match-expr-amp-amp-2(variant-literal-BOOL-1(x0:BoolV)) = bool(false) .
  eq match-expr-amp-amp-2(variant-id-ID-1(x0:Text)) = bool(false) .
  eq match-expr-amp-amp-2(variant-expr-bang-1(x0:Expr)) = bool(false) .
  eq match-expr-amp-amp-2(variant-expr-plus-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-amp-amp-2(variant-expr-lt-eq-2(x0:Expr, x1:Expr)) = bool(false) .
  eq match-expr-amp-amp-2(variant-expr-amp-amp-2(x0:Expr, x1:Expr)) = bool(true) .
  eq match-command-SKIP-0(variant-command-SKIP-0) = bool(true) .
  eq match-command-SKIP-0(variant-command-eq-3(x0:Type, x1:Id, x2:Expr)) = bool(false) .
  eq match-command-SKIP-0(variant-command-eq-2(x0:Id, x1:Expr)) = bool(false) .
  eq match-command-SKIP-0(variant-command-IF-THEN-ELSE-END-3(x0:Expr, x1:Command, x2:Command)) = bool(false) .
  eq match-command-SKIP-0(variant-command-WHILE-DO-END-2(x0:Expr, x1:Command)) = bool(false) .
  eq match-command-SKIP-0(variant-command-semi-2(x0:Command, x1:Command)) = bool(false) .
  eq match-command-eq-3(variant-command-SKIP-0) = bool(false) .
  eq match-command-eq-3(variant-command-eq-3(x0:Type, x1:Id, x2:Expr)) = bool(true) .
  eq match-command-eq-3(variant-command-eq-2(x0:Id, x1:Expr)) = bool(false) .
  eq match-command-eq-3(variant-command-IF-THEN-ELSE-END-3(x0:Expr, x1:Command, x2:Command)) = bool(false) .
  eq match-command-eq-3(variant-command-WHILE-DO-END-2(x0:Expr, x1:Command)) = bool(false) .
  eq match-command-eq-3(variant-command-semi-2(x0:Command, x1:Command)) = bool(false) .
  eq match-command-eq-2(variant-command-SKIP-0) = bool(false) .
  eq match-command-eq-2(variant-command-eq-3(x0:Type, x1:Id, x2:Expr)) = bool(false) .
  eq match-command-eq-2(variant-command-eq-2(x0:Id, x1:Expr)) = bool(true) .
  eq match-command-eq-2(variant-command-IF-THEN-ELSE-END-3(x0:Expr, x1:Command, x2:Command)) = bool(false) .
  eq match-command-eq-2(variant-command-WHILE-DO-END-2(x0:Expr, x1:Command)) = bool(false) .
  eq match-command-eq-2(variant-command-semi-2(x0:Command, x1:Command)) = bool(false) .
  eq match-command-IF-THEN-ELSE-END-3(variant-command-SKIP-0) = bool(false) .
  eq match-command-IF-THEN-ELSE-END-3(variant-command-eq-3(x0:Type, x1:Id, x2:Expr)) = bool(false) .
  eq match-command-IF-THEN-ELSE-END-3(variant-command-eq-2(x0:Id, x1:Expr)) = bool(false) .
  eq match-command-IF-THEN-ELSE-END-3(variant-command-IF-THEN-ELSE-END-3(x0:Expr, x1:Command, x2:Command)) = bool(true) .
  eq match-command-IF-THEN-ELSE-END-3(variant-command-WHILE-DO-END-2(x0:Expr, x1:Command)) = bool(false) .
  eq match-command-IF-THEN-ELSE-END-3(variant-command-semi-2(x0:Command, x1:Command)) = bool(false) .
  eq match-command-WHILE-DO-END-2(variant-command-SKIP-0) = bool(false) .
  eq match-command-WHILE-DO-END-2(variant-command-eq-3(x0:Type, x1:Id, x2:Expr)) = bool(false) .
  eq match-command-WHILE-DO-END-2(variant-command-eq-2(x0:Id, x1:Expr)) = bool(false) .
  eq match-command-WHILE-DO-END-2(variant-command-IF-THEN-ELSE-END-3(x0:Expr, x1:Command, x2:Command)) = bool(false) .
  eq match-command-WHILE-DO-END-2(variant-command-WHILE-DO-END-2(x0:Expr, x1:Command)) = bool(true) .
  eq match-command-WHILE-DO-END-2(variant-command-semi-2(x0:Command, x1:Command)) = bool(false) .
  eq match-command-semi-2(variant-command-SKIP-0) = bool(false) .
  eq match-command-semi-2(variant-command-eq-3(x0:Type, x1:Id, x2:Expr)) = bool(false) .
  eq match-command-semi-2(variant-command-eq-2(x0:Id, x1:Expr)) = bool(false) .
  eq match-command-semi-2(variant-command-IF-THEN-ELSE-END-3(x0:Expr, x1:Command, x2:Command)) = bool(false) .
  eq match-command-semi-2(variant-command-WHILE-DO-END-2(x0:Expr, x1:Command)) = bool(false) .
  eq match-command-semi-2(variant-command-semi-2(x0:Command, x1:Command)) = bool(true) .
  eq $itermap-K-t-minus-gt-V-t-list-2-pair(nil, nil) = nil .
  eq $itermap-K-t-minus-gt-V-t-list-2-pair(cons(K-t--hd:Val, K-t--tl:List), cons(V-t--hd:Val, V-t--tl:List)) = cons(variant-pair-minus-gt-2(K-t--hd:Val, V-t--hd:Val), $itermap-K-t-minus-gt-V-t-list-2-pair(K-t--tl:List, V-t--tl:List)) .
  eq $unzip-K-t-minus-gt-V-t-list-V-t(nil) = nil .
  eq $unzip-K-t-minus-gt-V-t-list-V-t(cons(variant-pair-minus-gt-2(K-t--hd:Val, V-t--hd:Val), --rest:List)) = cons(V-t--hd:Val, $unzip-K-t-minus-gt-V-t-list-V-t(--rest:List)) .
  eq $unzip-K-t-minus-gt-V-t-list-K-t(nil) = nil .
  eq $unzip-K-t-minus-gt-V-t-list-K-t(cons(variant-pair-minus-gt-2(K-t--hd:Val, V-t--hd:Val), --rest:List)) = cons(K-t--hd:Val, $unzip-K-t-minus-gt-V-t-list-K-t(--rest:List)) .
  eq subty-literal(variant-id-ID-1(x0:Text)) = bool(false) .
  eq subty-literal(variant-expr-bang-1(x0:Expr)) = bool(false) .
  eq subty-literal(variant-expr-plus-2(x0:Expr, x1:Expr)) = bool(false) .
  eq subty-literal(variant-expr-lt-eq-2(x0:Expr, x1:Expr)) = bool(false) .
  eq subty-literal(variant-expr-amp-amp-2(x0:Expr, x1:Expr)) = bool(false) .
  eq subty-id(variant-literal-NUM-1(x0:IntV)) = bool(false) .
  eq subty-id(variant-literal-BOOL-1(x0:BoolV)) = bool(false) .
  eq subty-id(variant-expr-bang-1(x0:Expr)) = bool(false) .
  eq subty-id(variant-expr-plus-2(x0:Expr, x1:Expr)) = bool(false) .
  eq subty-id(variant-expr-lt-eq-2(x0:Expr, x1:Expr)) = bool(false) .
  eq subty-id(variant-expr-amp-amp-2(x0:Expr, x1:Expr)) = bool(false) .
  ceq $lookup(pair-lt-K-comma-V-gt:List, K-query:Val) = none if match-nil(pair-lt-K-comma-V-gt:List) = bool(true) .
  ceq $lookup(pair-lt-K-comma-V-gt:List, K-query:Val) = some(V-h:Val) if match-cons(pair-lt-K-comma-V-gt:List) = bool(true) /\ cons(variant-pair-minus-gt-2(K-h:Val, V-h:Val), iterbind-0:List) := pair-lt-K-comma-V-gt:List /\ K-t:Val := $unzip-K-t-minus-gt-V-t-list-K-t(iterbind-0:List) /\ isStuckHead(K-t:Val) = false /\ V-t:Val := $unzip-K-t-minus-gt-V-t-list-V-t(iterbind-0:List) /\ isStuckHead(V-t:Val) = false /\ K-h:Val = K-query:Val .
  ceq $lookup(pair-lt-K-comma-V-gt:List, K-query:Val) = $lookup($itermap-K-t-minus-gt-V-t-list-2-pair(K-t:Val, V-t:Val), K-query:Val) if match-cons(pair-lt-K-comma-V-gt:List) = bool(true) /\ cons(variant-pair-minus-gt-2(K-h:Val, V-h:Val), iterbind-0:List) := pair-lt-K-comma-V-gt:List /\ K-t:Val := $unzip-K-t-minus-gt-V-t-list-K-t(iterbind-0:List) /\ isStuckHead(K-t:Val) = false /\ V-t:Val := $unzip-K-t-minus-gt-V-t-list-V-t(iterbind-0:List) /\ isStuckHead(V-t:Val) = false [owise] .
  ceq Check-expr(tenv:List, expr:Expr) = variant-type-INT-0 if subty-literal(expr:Expr) = bool(true) /\ literal:Literal := expr:Expr /\ match-literal-NUM-1(literal:Literal) = bool(true) /\ variant-literal-NUM-1(i:IntV) := literal:Literal .
  ceq Check-expr(tenv:List, expr:Expr) = variant-type-BOOL-0 if subty-literal(expr:Expr) = bool(true) /\ literal:Literal := expr:Expr /\ match-literal-BOOL-1(literal:Literal) = bool(true) /\ variant-literal-BOOL-1(b:BoolV) := literal:Literal .
  ceq Check-expr(tenv:List, expr:Expr) = t:Type if subty-id(expr:Expr) = bool(true) /\ x:Id := expr:Expr /\ type:Opt := $lookup(tenv:List, x:Id) /\ isStuckHead(type:Opt) = false /\ match-some(type:Opt) = bool(true) /\ some(t:Type) := type:Opt .
  ceq Check-expr(tenv:List, expr:Expr) = variant-type-BOOL-0 if match-expr-bang-1(expr:Expr) = bool(true) /\ variant-expr-bang-1(e:Expr) := expr:Expr /\ type:Type := Check-expr(tenv:List, e:Expr) /\ isStuckHead(type:Type) = false /\ match-type-BOOL-0(type:Type) = bool(true) .
  ceq Check-expr(tenv:List, expr:Expr) = variant-type-INT-0 if match-expr-plus-2(expr:Expr) = bool(true) /\ variant-expr-plus-2(e-l:Expr, e-r:Expr) := expr:Expr /\ type:Type := Check-expr(tenv:List, e-l:Expr) /\ isStuckHead(type:Type) = false /\ match-type-INT-0(type:Type) = bool(true) /\ type-prime:Type := Check-expr(tenv:List, e-r:Expr) /\ isStuckHead(type-prime:Type) = false /\ match-type-INT-0(type-prime:Type) = bool(true) .
  ceq Check-expr(tenv:List, expr:Expr) = variant-type-BOOL-0 if match-expr-lt-eq-2(expr:Expr) = bool(true) /\ variant-expr-lt-eq-2(e-l:Expr, e-r:Expr) := expr:Expr /\ type:Type := Check-expr(tenv:List, e-l:Expr) /\ isStuckHead(type:Type) = false /\ match-type-INT-0(type:Type) = bool(true) /\ type-prime:Type := Check-expr(tenv:List, e-r:Expr) /\ isStuckHead(type-prime:Type) = false /\ match-type-INT-0(type-prime:Type) = bool(true) .
  ceq Check-expr(tenv:List, expr:Expr) = variant-type-BOOL-0 if match-expr-amp-amp-2(expr:Expr) = bool(true) /\ variant-expr-amp-amp-2(e-l:Expr, e-r:Expr) := expr:Expr /\ type:Type := Check-expr(tenv:List, e-l:Expr) /\ isStuckHead(type:Type) = false /\ match-type-BOOL-0(type:Type) = bool(true) /\ type-prime:Type := Check-expr(tenv:List, e-r:Expr) /\ isStuckHead(type-prime:Type) = false /\ match-type-BOOL-0(type-prime:Type) = bool(true) .
  ceq Check-command(tenv:List, command:Command) = tenv:List if match-command-SKIP-0(command:Command) = bool(true) .
  ceq Check-command(tenv:List, command:Command) = cons(variant-pair-minus-gt-2(x:Id, t:Type), tenv:List) if match-command-eq-3(command:Command) = bool(true) /\ variant-command-eq-3(t:Type, x:Id, e:Expr) := command:Command /\ type:Type := Check-expr(tenv:List, e:Expr) /\ isStuckHead(type:Type) = false /\ type:Type = t:Type .
  ceq Check-command(tenv:List, command:Command) = tenv:List if match-command-eq-2(command:Command) = bool(true) /\ variant-command-eq-2(x:Id, e:Expr) := command:Command /\ t:Type := Check-expr(tenv:List, e:Expr) /\ isStuckHead(t:Type) = false /\ $lookup(tenv:List, x:Id) = some(t:Type) .
  ceq Check-command(tenv:List, command:Command) = tenv:List if match-command-IF-THEN-ELSE-END-3(command:Command) = bool(true) /\ variant-command-IF-THEN-ELSE-END-3(e:Expr, c-1:Command, c-2:Command) := command:Command /\ type:Type := Check-expr(tenv:List, e:Expr) /\ isStuckHead(type:Type) = false /\ match-type-BOOL-0(type:Type) = bool(true) /\ tenv-1:List := Check-command(tenv:List, c-1:Command) /\ isStuckHead(tenv-1:List) = false /\ tenv-2:List := Check-command(tenv:List, c-2:Command) /\ isStuckHead(tenv-2:List) = false .
  ceq Check-command(tenv:List, command:Command) = tenv:List if match-command-WHILE-DO-END-2(command:Command) = bool(true) /\ variant-command-WHILE-DO-END-2(e:Expr, c:Command) := command:Command /\ type:Type := Check-expr(tenv:List, e:Expr) /\ isStuckHead(type:Type) = false /\ match-type-BOOL-0(type:Type) = bool(true) /\ tenv-1:List := Check-command(tenv:List, c:Command) /\ isStuckHead(tenv-1:List) = false .
  ceq Check-command(tenv:List, command:Command) = tenv-2:List if match-command-semi-2(command:Command) = bool(true) /\ variant-command-semi-2(c-1:Command, c-2:Command) := command:Command /\ tenv-1:List := Check-command(tenv:List, c-1:Command) /\ isStuckHead(tenv-1:List) = false /\ tenv-2:List := Check-command(tenv-1:List, c-2:Command) /\ isStuckHead(tenv-2:List) = false .
  ceq Check-prog(command:Command) = bool(true) if tenv:List := Check-command(nil, command:Command) /\ isStuckHead(tenv:List) = false .
  ceq Eval-expr(env:List, expr:Expr) = variant-literal-NUM-1(i:IntV) if subty-literal(expr:Expr) = bool(true) /\ literal:Literal := expr:Expr /\ match-literal-NUM-1(literal:Literal) = bool(true) /\ variant-literal-NUM-1(i:IntV) := literal:Literal .
  ceq Eval-expr(env:List, expr:Expr) = variant-literal-BOOL-1(b:BoolV) if subty-literal(expr:Expr) = bool(true) /\ literal:Literal := expr:Expr /\ match-literal-BOOL-1(literal:Literal) = bool(true) /\ variant-literal-BOOL-1(b:BoolV) := literal:Literal .
  ceq Eval-expr(env:List, expr:Expr) = v:Literal if subty-id(expr:Expr) = bool(true) /\ x:Id := expr:Expr /\ value:Opt := $lookup(env:List, x:Id) /\ isStuckHead(value:Opt) = false /\ match-some(value:Opt) = bool(true) /\ some(v:Literal) := value:Opt .
  ceq Eval-expr(env:List, expr:Expr) = variant-literal-BOOL-1(b:BoolV) if match-expr-bang-1(expr:Expr) = bool(true) /\ variant-expr-bang-1(e:Expr) := expr:Expr /\ literal:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(literal:Literal) = false /\ match-literal-BOOL-1(literal:Literal) = bool(true) /\ variant-literal-BOOL-1(b-e:BoolV) := literal:Literal /\ b:BoolV := not(b-e:BoolV) /\ isStuckHead(b:BoolV) = false .
  ceq Eval-expr(env:List, expr:Expr) = variant-literal-NUM-1(i:IntV) if match-expr-plus-2(expr:Expr) = bool(true) /\ variant-expr-plus-2(e-l:Expr, e-r:Expr) := expr:Expr /\ literal:Literal := Eval-expr(env:List, e-l:Expr) /\ isStuckHead(literal:Literal) = false /\ match-literal-NUM-1(literal:Literal) = bool(true) /\ variant-literal-NUM-1(i-l:IntV) := literal:Literal /\ literal-prime:Literal := Eval-expr(env:List, e-r:Expr) /\ isStuckHead(literal-prime:Literal) = false /\ match-literal-NUM-1(literal-prime:Literal) = bool(true) /\ variant-literal-NUM-1(i-r:IntV) := literal-prime:Literal /\ i:IntV := add-int(i-l:IntV, i-r:IntV) /\ isStuckHead(i:IntV) = false .
  ceq Eval-expr(env:List, expr:Expr) = variant-literal-BOOL-1(b:BoolV) if match-expr-lt-eq-2(expr:Expr) = bool(true) /\ variant-expr-lt-eq-2(e-l:Expr, e-r:Expr) := expr:Expr /\ literal:Literal := Eval-expr(env:List, e-l:Expr) /\ isStuckHead(literal:Literal) = false /\ match-literal-NUM-1(literal:Literal) = bool(true) /\ variant-literal-NUM-1(i-l:IntV) := literal:Literal /\ literal-prime:Literal := Eval-expr(env:List, e-r:Expr) /\ isStuckHead(literal-prime:Literal) = false /\ match-literal-NUM-1(literal-prime:Literal) = bool(true) /\ variant-literal-NUM-1(i-r:IntV) := literal-prime:Literal /\ b:BoolV := leq-int(i-l:IntV, i-r:IntV) /\ isStuckHead(b:BoolV) = false .
  ceq Eval-expr(env:List, expr:Expr) = variant-literal-BOOL-1(b:BoolV) if match-expr-amp-amp-2(expr:Expr) = bool(true) /\ variant-expr-amp-amp-2(e-l:Expr, e-r:Expr) := expr:Expr /\ literal:Literal := Eval-expr(env:List, e-l:Expr) /\ isStuckHead(literal:Literal) = false /\ match-literal-BOOL-1(literal:Literal) = bool(true) /\ variant-literal-BOOL-1(b-l:BoolV) := literal:Literal /\ literal-prime:Literal := Eval-expr(env:List, e-r:Expr) /\ isStuckHead(literal-prime:Literal) = false /\ match-literal-BOOL-1(literal-prime:Literal) = bool(true) /\ variant-literal-BOOL-1(b-r:BoolV) := literal-prime:Literal /\ b:BoolV := and(b-l:BoolV, b-r:BoolV) /\ isStuckHead(b:BoolV) = false .
  ceq Eval-command(env:List, command:Command) = env:List if match-command-SKIP-0(command:Command) = bool(true) .
  ceq Eval-command(env:List, command:Command) = cons(variant-pair-minus-gt-2(x:Id, v:Literal), env:List) if match-command-eq-3(command:Command) = bool(true) /\ variant-command-eq-3(t:Type, x:Id, e:Expr) := command:Command /\ v:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(v:Literal) = false .
  ceq Eval-command(env:List, command:Command) = cons(variant-pair-minus-gt-2(x:Id, v:Literal), env:List) if match-command-eq-2(command:Command) = bool(true) /\ variant-command-eq-2(x:Id, e:Expr) := command:Command /\ v:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(v:Literal) = false .
  ceq Eval-command(env:List, command:Command) = env-1:List if match-command-IF-THEN-ELSE-END-3(command:Command) = bool(true) /\ variant-command-IF-THEN-ELSE-END-3(e:Expr, c-1:Command, c-2:Command) := command:Command /\ literal:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(literal:Literal) = false /\ literal:Literal = variant-literal-BOOL-1(bool(true)) /\ env-1:List := Eval-command(env:List, c-1:Command) /\ isStuckHead(env-1:List) = false .
  ceq Eval-command(env:List, command:Command) = env-2:List if match-command-IF-THEN-ELSE-END-3(command:Command) = bool(true) /\ variant-command-IF-THEN-ELSE-END-3(e:Expr, c-1:Command, c-2:Command) := command:Command /\ literal:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(literal:Literal) = false /\ literal:Literal = variant-literal-BOOL-1(bool(false)) /\ env-2:List := Eval-command(env:List, c-2:Command) /\ isStuckHead(env-2:List) = false .
  ceq Eval-command(env:List, command:Command) = env:List if match-command-WHILE-DO-END-2(command:Command) = bool(true) /\ variant-command-WHILE-DO-END-2(e:Expr, c:Command) := command:Command /\ literal:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(literal:Literal) = false /\ literal:Literal = variant-literal-BOOL-1(bool(false)) .
  ceq Eval-command(env:List, command:Command) = env-2:List if match-command-WHILE-DO-END-2(command:Command) = bool(true) /\ variant-command-WHILE-DO-END-2(e:Expr, c:Command) := command:Command /\ literal:Literal := Eval-expr(env:List, e:Expr) /\ isStuckHead(literal:Literal) = false /\ literal:Literal = variant-literal-BOOL-1(bool(true)) /\ env-1:List := Eval-command(env:List, c:Command) /\ isStuckHead(env-1:List) = false /\ env-2:List := Eval-command(env-1:List, variant-command-WHILE-DO-END-2(e:Expr, c:Command)) /\ isStuckHead(env-2:List) = false .
  ceq Eval-command(env:List, command:Command) = env-2:List if match-command-semi-2(command:Command) = bool(true) /\ variant-command-semi-2(c-1:Command, c-2:Command) := command:Command /\ env-1:List := Eval-command(env:List, c-1:Command) /\ isStuckHead(env-1:List) = false /\ env-2:List := Eval-command(env-1:List, c-2:Command) /\ isStuckHead(env-2:List) = false .
  ceq Eval-prog(command:Command) = env:List if env:List := Eval-command(nil, command:Command) /\ isStuckHead(env:List) = false .
  ceq Run-prog(command:Command) = env:List if Check-prog(command:Command) = bool(true) /\ env:List := Eval-prog(command:Command) /\ isStuckHead(env:List) = false .

  eq add-int(int(I:Int), int(J:Int)) = int(I:Int + J:Int) .
  eq and(bool(true), Y:Val) = Y:Val .
  eq and(bool(false), Y:Val) = bool(false) .
  eq leq-int(int(I:Int), int(J:Int)) = bool(I:Int <= J:Int) .
  eq not(bool(B:Bool)) = bool(not B:Bool) .

  ceq subty-id(X0:Val) = bool(false) if isStuckHead(X0:Val) = false [owise] .
  ceq subty-literal(X0:Val) = bool(false) if isStuckHead(X0:Val) = false [owise] .

  eq isStuckHead($itermap-K-t-minus-gt-V-t-list-2-pair(V0:Val, V1:Val)) = true .
  eq isStuckHead($lookup(V0:List, V1:Val)) = true .
  eq isStuckHead($unzip-K-t-minus-gt-V-t-list-K-t(V0:Val)) = true .
  eq isStuckHead($unzip-K-t-minus-gt-V-t-list-V-t(V0:Val)) = true .
  eq isStuckHead(Check-command(V0:List, V1:Command)) = true .
  eq isStuckHead(Check-expr(V0:List, V1:Expr)) = true .
  eq isStuckHead(Check-prog(V0:Command)) = true .
  eq isStuckHead(Eval-command(V0:List, V1:Command)) = true .
  eq isStuckHead(Eval-expr(V0:List, V1:Expr)) = true .
  eq isStuckHead(Eval-prog(V0:Command)) = true .
  eq isStuckHead(Run-prog(V0:Command)) = true .
  eq isStuckHead(add-int(V0:IntV, V1:IntV)) = true .
  eq isStuckHead(and(V0:BoolV, V1:BoolV)) = true .
  eq isStuckHead(leq-int(V0:IntV, V1:IntV)) = true .
  eq isStuckHead(match-command-IF-THEN-ELSE-END-3(V0:Command)) = true .
  eq isStuckHead(match-command-SKIP-0(V0:Command)) = true .
  eq isStuckHead(match-command-WHILE-DO-END-2(V0:Command)) = true .
  eq isStuckHead(match-command-eq-2(V0:Command)) = true .
  eq isStuckHead(match-command-eq-3(V0:Command)) = true .
  eq isStuckHead(match-command-semi-2(V0:Command)) = true .
  eq isStuckHead(match-cons(V0:List)) = true .
  eq isStuckHead(match-expr-amp-amp-2(V0:Expr)) = true .
  eq isStuckHead(match-expr-bang-1(V0:Expr)) = true .
  eq isStuckHead(match-expr-lt-eq-2(V0:Expr)) = true .
  eq isStuckHead(match-expr-plus-2(V0:Expr)) = true .
  eq isStuckHead(match-literal-BOOL-1(V0:Literal)) = true .
  eq isStuckHead(match-literal-NUM-1(V0:Literal)) = true .
  eq isStuckHead(match-nil(V0:List)) = true .
  eq isStuckHead(match-some(V0:Opt)) = true .
  eq isStuckHead(match-type-BOOL-0(V0:Type)) = true .
  eq isStuckHead(match-type-INT-0(V0:Type)) = true .
  eq isStuckHead(not(V0:BoolV)) = true .
  eq isStuckHead(subty-id(V0:Val)) = true .
  eq isStuckHead(subty-literal(V0:Val)) = true .
  eq isStuckHead(D:Val) = false [owise] .
endm

